### ISSUE TITLE
Error within vagrant 

### ISSUE THREAD

**Issue by miketamis** [kimmobrunfeldt/git-hours#12]
After following the vagrant instruction:
```console
$ git clone https://github.com/kimmobrunfeldt/git-hours
$ cd git-hours
$ vagrant up && vagrant ssh
```

I clone a repo and tried git hours.

```console
vagrant@git-hours:~/electron$ git hours

module.js:340
    throw err;
          ^
Error: Cannot find module '../build/Debug/nodegit.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/git-hours/node_modules/nodegit/lib/nodegit.js:16:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/git-hours/src/index.js:4:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by fabiosoft** [comment]
I solved here. #13

**Comment by kimmobrunfeldt** [comment]
@fabiosoft's pull request is now merged to master, it works.
