### ISSUE TITLE
Git hours does not work on Node 5.4.0

### ISSUE THREAD

**Issue by ykarikos** [kimmobrunfeldt/git-hours#14]
I have Node 5.4.0, installed from homebrew on OS X 10.11.2. Git hours install succeeds but it does not work.

```
$ node -v
v5.4.0
$ npm install -g git-hours
/usr/local/bin/git-hours -> /usr/local/lib/node_modules/git-hours/src/index.js

> nodegit@0.4.1 install /usr/local/lib/node_modules/git-hours/node_modules/nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary, building manually.
[nodegit] Making sure dependencies are available and native code is generated
[nodegit] Something is missing, retrieving dependencies and regenerating code
nodegit@0.4.1 /usr/local/lib/node_modules/nodegit
├── promisify-node@0.1.5 (nodegit-promise@1.0.2)
├── nodegit-promise@2.0.1 (asap@2.0.3)
├── which-native-nodish@1.1.3 (find-parent-dir@0.3.0, nodegit-promise@1.0.2)
├── fs-extra@0.18.4 (jsonfile@2.2.3, graceful-fs@3.0.8, rimraf@2.5.0)
└── npm@2.14.15

/usr/local/lib
`-- git-hours@1.1.0
  +-- bluebird@2.10.2
  +-- commander@2.9.0
  | `-- graceful-readlink@1.0.1
  +-- lodash@2.4.2
  +-- moment@2.11.1
  `-- nodegit@0.4.1
    +-- fs-extra@0.18.4
    | +-- graceful-fs@3.0.8
    | +-- jsonfile@2.2.3
    | `-- rimraf@2.5.0
    |   `-- glob@6.0.4
    |     +-- inflight@1.0.4
    |     | `-- wrappy@1.0.1
    |     +-- inherits@2.0.1
    |     +-- minimatch@3.0.0
    |     | `-- brace-expansion@1.1.2
    |     |   +-- balanced-match@0.3.0
    |     |   `-- concat-map@0.0.1
    |     +-- once@1.3.3
    |     `-- path-is-absolute@1.0.0
    +-- node-pre-gyp@0.6.7
    | +-- npmlog@1.2.0
    | | `-- are-we-there-yet@1.0.4
    | |   `-- readable-stream@1.1.13
    | |     `-- inherits@2.0.1
    | +-- request@2.55.0
    | | +-- bl@0.9.4
    | | | `-- readable-stream@1.0.33
    | | |   `-- inherits@2.0.1
    | | `-- har-validator@1.7.0
    | |   `-- commander@2.8.1
    | |     `-- graceful-readlink@1.0.1
    | +-- rimraf@2.3.3
    | | `-- glob@4.5.3
    | |   +-- inflight@1.0.4
    | |   | `-- wrappy@1.0.1
    | |   +-- inherits@2.0.1
    | |   +-- minimatch@2.0.7
    | |   | `-- brace-expansion@1.1.0
    | |   |   `-- concat-map@0.0.1
    | |   `-- once@1.3.1
    | |     `-- wrappy@1.0.1
    | +-- tar@2.1.0
    | | `-- inherits@2.0.1
    | `-- tar-pack@2.0.0
    |   +-- fstream@0.1.31
    |   | `-- inherits@2.0.1
    |   +-- fstream-ignore@0.0.7
    |   | `-- inherits@2.0.1
    |   +-- readable-stream@1.0.33
    |   | `-- inherits@2.0.1
    |   `-- tar@0.1.20
    |     `-- inherits@2.0.1
    +-- nodegit-promise@2.0.1
    | `-- asap@2.0.3
    +-- npm@2.14.15
    | +-- cmd-shim@2.0.1
    | | `-- graceful-fs@3.0.8
    | +-- dezalgo@1.0.3
    | | `-- asap@2.0.3
    | +-- glob@5.0.15
    | | `-- path-is-absolute@1.0.0
    | +-- inflight@1.0.4
    | +-- inherits@2.0.1
    | +-- minimatch@3.0.0
    | | `-- brace-expansion@1.1.1
    | |   `-- concat-map@0.0.1
    | +-- node-gyp@3.2.1
    | | `-- glob@4.5.3
    | |   `-- minimatch@2.0.10
    | |     `-- brace-expansion@1.1.2
    | |       +-- balanced-match@0.3.0
    | |       `-- concat-map@0.0.1
    | +-- once@1.3.3
    | +-- request@2.67.0
    | | `-- har-validator@2.0.3
    | |   `-- commander@2.9.0
    | |     `-- graceful-readlink@1.0.1
    | `-- wrappy@1.0.1
    +-- promisify-node@0.1.5
    | `-- nodegit-promise@1.0.2
    |   `-- asap@1.0.0
    `-- which-native-nodish@1.1.3
      +-- find-parent-dir@0.3.0
      `-- nodegit-promise@1.0.2
        `-- asap@1.0.0

$ git hours
module.js:328
    throw err;
    ^

Error: Cannot find module '../build/Debug/nodegit.node'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/git-hours/node_modules/nodegit/lib/nodegit.js:16:12)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/git-hours/src/index.js:4:11)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
```

**Comment by kimmobrunfeldt** [comment]
Let's continue the issue here https://github.com/kimmobrunfeldt/git-hours/issues/15
