### ISSUE TITLE
Vagrant Test Fails

### ISSUE THREAD

**Issue by lacostenycoder** [kimmobrunfeldt/git-hours#31]
I didn't try installing via NPM but followed instructions to test with vagrant.  Got an error, also tried installing nodegit inside the vagrant vb, both before and after install nodegit I got the following error:

```
vagrant@vagrant-ubuntu-trusty-64:~/bootstrap$ git hours
module.js:338
    throw err;
          ^
Error: Cannot find module '../build/Debug/nodegit.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/git-hours/node_modules/nodegit/dist/nodegit.js:18:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/git-hours/src/index.js:4:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by hcrub** [comment]
+1

**Comment by variousauthors** [comment]
I installed via npm v4.2.0 on OSX 10.12.4 and got the same.

**Comment by hdsenevi** [comment]
Same happens to me as well

macOS Sierra (10.12.5)
npm 5.0.3
node v8.0.0

**Comment by PhilAlton** [comment]
Had the same problem, and have found a work around:
1) Install nodegit manually (run npm install -g nodegit [as an administrator / i.e. sudo or cmd with admin privileges])

2) Locate the node_modules root directory (should now include both nodegit and git-hours). Navigate into nodegit's build folder and copy the release folder. Now navigate to the node_modules/git-hours folder, and then to git-hour's node_modules folder (which will contain a nodegit folder). Replace the git-hours\node_modules\nodegit\build\Release folder with the Release folder from node_modules\nodegit\build\Release. Furthermore, copy the folder again to the same directory, but this time name it Debug, not Release.

3). Try running git hours again, from within your chosen git repo.

**Comment by NiavlysB** [comment]
@PhilAlton Many thanks, this works for me as well! (not using Vagrant, simply the npm install for `git-hours` and `nodegit`)

**Comment by kimmobrunfeldt** [comment]
Vagrant setup is now out of scope for this repo, updated the instructions.
