### ISSUE TITLE
Errors finding modules after install

### ISSUE THREAD

**Issue by appsird** [kimmobrunfeldt/git-hours#42]
I first installed Vagrant and VirtualBox

installed Vagrant on macOS 10.14.6
installed VirtualBox on macOS 10.14.6

Then I installed git-hours:

https://github.com/kimmobrunfeldt/git-hours
cd git-hours
vagrant up && vagrant ssh

I then needed to install git inside the ssh session. Then I attempted to access my git repo

git clone https://github.com/appsird/iAmp-xxxx.git
user:
pw:
cd iAmp-xxxx
git hours

I received a missing module error - and many others on Google search had this same error for different reasons. Is there a means to run this application without dependencies for a VM OS and other pieces. Can I run directly in macOS, which is Debian instead?

```swift
vagrant@vagrant-ubuntu-trusty-64:~/iAmp-iOS-13$ git hours
module.js:338
    throw err;
          ^
Error: Cannot find module '../build/Debug/nodegit.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/git-hours/node_modules/nodegit/dist/nodegit.js:18:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/git-hours/src/index.js:4:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
vagrant@vagrant-ubuntu-trusty-64:~/iAmp-iOS-13$ 

```

**Comment by appsird** [comment]
These are the errors I received when running

vagrant up && vagrant ssh

<img width="1279" alt="Screen Shot 2019-08-18 at 12 38 15 PM" src="https://user-images.githubusercontent.com/8471833/63229451-283f7700-c1b5-11e9-9bd6-5bee1fb1b3aa.png">

**Comment by hristo-vrigazov** [comment]
Same issue for me on Ubuntu 18.04

**Comment by kimmobrunfeldt** [comment]
I haven't used the Vagrant setup so can't help with this one. I'm closing this since Vagrant and Docker setups are now out of scope for this repo. The guides were old and unmaintained.
